### Import Libraries and Install

In [1]:
import requests
from bs4 import BeautifulSoup
from fake_useragent import UserAgent
import pandas as pd

## Scraping dev.to

In [5]:
url = 'https://dev.to/'

ua = UserAgent()
userAgent = ua.random
headers = {'User-Agent': userAgent}
page = requests.get(url, headers = headers)
soup = BeautifulSoup(page.content, "html.parser")
print(url)
blog_box = soup.find_all('div', class_= "crayons-story")

links = []
titles = []
time_uploaded = []
authors = []
tags = []
reading_times = []

for box in blog_box:
    #links
    if box.find('h2', class_ = "crayons-story__title") is not None:
        link = box.find('h2', class_ = "crayons-story__title").a  #.replace('\n\t\t','').replace('\n','').strip()
        link = link['href']
        links.append(link)
    else:
        links.append('None')

    #titles
    if box.find('h2', class_ = "crayons-story__title") is not None:
        title = box.find('h2', class_ = "crayons-story__title").text.replace('\n','').strip()
        titles.append(title)
    else:
        titles.append('None')

    #time_uploaded
    if box.find('time', attrs={"datetime": True}) is not None:
        time_upload = box.find('time', attrs={"datetime": True})   #.replace('\n\t\t','').replace('\n','').strip()
        time_upload = time_upload['datetime']
        time_uploaded.append(time_upload)
    else:
        time_uploaded.append('None') 

    #author
    if box.find('a', class_ ="crayons-story__secondary fw-medium m:hidden") is not None:
        author = box.find('a', class_ ="crayons-story__secondary fw-medium m:hidden").text.replace('\n','').strip()
        authors.append(author)
    else:
        authors.append('None')

    #tags
    if box.find('div', class_ ="crayons-story__tags") is not None:
        tag = box.find('div', class_ ="crayons-story__tags").text.replace('\n','').strip()
        tags.append(tag)
    else:
        tags.append('None')

    #reading_time
    if box.find('div', class_ ="crayons-story__save") is not None:
        reading_time = box.find('div', class_ ="crayons-story__save").text.replace('\n','').strip()
        reading_times.append(reading_time)
    else:
        reading_times.append('None')

df = pd.DataFrame({
    'Link': links,
    'Title': titles,
    'Time Uploaded': time_uploaded,
    'Author': authors,
    'Tags': tags,
    'Reading Time': reading_times
})

df_cleaned = df[df['Link'] != 'None']

article = []
article_link = []
def get_full_content(url): 
    ua = UserAgent()
    userAgent = ua.random
    headers = {'User-Agent': userAgent}
    page = requests.get(url, headers = headers)
    soup = BeautifulSoup(page.content, "html.parser")
    print(url)
    content = soup.find('div', class_= "crayons-article__body text-styles spec__body")
    paragraphs = content.find_all('p')
    contents = []
    # Iterate over each <p> tag and remove any <a> tags within them
    for paragraph in paragraphs:
        for a in paragraph.find_all('a'):
            a.decompose()  # Removes <a> tag and its content

    # Print the cleaned text from each <p> tag
    for paragraph in paragraphs:
        contents.append(paragraph.get_text())

    string = ' '.join(contents)
    article.append(string)
    article_link.append(url)

for i in df_cleaned.Link:
    get_full_content(i)


article_df = pd.DataFrame({
    'Article Content': article,
    'Link': article_link
})


merged_df = pd.merge(df_cleaned, article_df, on='Link', how='inner')
merged_df

https://dev.to/
https://dev.to/devteam/happy-11111101001-join-our-new-year-writing-challenge-43g4
https://dev.to/sholajegede/part-2-master-authentication-and-role-based-access-control-rbac-with-kinde-and-convex-in-a-ch
https://dev.to/jetthoughts/why-ai-hasnt-blown-our-mindsyet-1f7e
https://dev.to/resource_bunk_1077cab07da/why-most-notion-templates-fail-businesses-and-how-to-create-ones-that-work-4jnd
https://dev.to/0x3d_site/25-golang-resources-every-developer-will-find-helpful-and-interesting-1ooh
https://dev.to/sonaykara/react-keeping-components-pure-32jn
https://dev.to/lovestaco/building-a-login-component-with-ssr-support-using-solidjs-15oj
https://dev.to/hanzla-baig/upcoming-challenges-on-devto-3434
https://dev.to/kiraaziz/i-hate-website-builders-so-i-built-my-own-1728
https://dev.to/makechi02/2024-a-year-of-resilience-learning-and-growth-5h3d
https://dev.to/kcatucuamba/dominio-personalizado-en-amazon-api-gateway-dominio-desde-godaddy-cm1
https://dev.to/eunit/five-advanced-techniques-to-improve-automated-testing-by-50-ccf
https://dev.to/shrsv/price-wage-profit-rent-14p7
https://dev.to/dhanushnehru/dev-retro-2024-journey-in-review-2i4d
https://dev.to/chiragcodesweb/building-a-scalable-reverse-proxy-server-like-nginx-with-nodejs-and-typescript-3h4n
https://dev.to/yokwejuste/how-to-scan-in-golang-5gk0
https://dev.to/yokwejuste/how-to-print-in-golang-fhh

https://dev.to/stdlib/2024-retrospective-pip
https://dev.to/kiran_baliga/retroing-and-debugging-2024-my-journey-of-growth-and-resilience-147o
https://dev.to/dubjay18/the-power-of-context-in-go-a-guide-to-efficient-code-execution-jl
https://dev.to/harshm03/introduction-to-database-management-systems-29pe
https://dev.to/alvaromontoro/human-writing-in-the-age-of-ai-55oo
https://dev.to/okerew/new-version-for-my-osxiec-project-2pkm
https://dev.to/youneshajizadeh/unpacking-the-benefits-and-pitfalls-of-typescript-jf6
https://dev.to/saidmounaim/dev-next-is-a-job-platform-built-with-nextjs-tailwind-css-prisma-and-nextauth-1f4e
https://dev.to/toptech5419/-week-11-of-100daysofcode-responsive-designs-css-grid-and-solo-projects-216l
https://dev.to/ahelmy/unlock-the-power-of-docusaurus-with-ai-3clk
https://dev.to/franciscomoretti/color-highlighting-for-tailwind-css-variables-in-vs-code-371n
https://dev.to/georgoulis/what-kind-of-data-team-should-i-join-1e4l
https://dev.to/dubjay18/gos-must-pattern-streamline-your-error-handling-27ff
https://dev.to/pahlavaubivca/rust-registry-error-candidate-versions-found-which-didnt-match-206p
https://dev.to/mikhailepatko/how-to-implement-jacoco-in-kotlin-spring-boot-gradle-project-2ffb
https://dev.to/zerk4/laravel-debugbar-for-nextjs-326m
https://dev.to/rodbv/creating-a-to-do-app-with-django-and-htmx-part-6-implementing-delete-with-tdd-471l
https://dev.to/madgan95/interface-standard-overview-1b7j
https://dev.to/vishaaxl/build-an-otp-based-authentication-server-with-go-part-1-760
https://dev.to/master_mentee/how-i-set-up-my-custom-domain-and-email-for-substack-57b8
https://dev.to/blessedtechnologist/understanding-proof-of-work-in-blockchain-l2k
https://dev.to/mellen/2025-what-is-it-good-for-5flo
https://dev.to/josemariairiarte/first-steps-with-c-an-introductory-capstone-project-455k
https://dev.to/sourav_22cdd152890952704c/mastering-langchain-simplifying-complex-development-for-modern-apps-10jg
https://dev.to/cheedge_lee/clusterip-vs-nodeport-4cm
https://dev.to/sourav_22cdd152890952704c/react-19-unleashed-new-features-every-developer-must-know-5bp5
https://dev.to/yencolon/understanding-spring-security-building-an-authentication-flow-in-less-than-a-day-bm
https://dev.to/razbakov/my-journey-with-ai-agents-revolutionizing-wedance-development-5a5
https://dev.to/airabbit/stop-repeating-terminal-command-ask-ai-13g8
https://dev.to/xwero/laravel-route-alternatives-53pl
https://dev.to/emiroberti/aws-lambda-and-its-invocation-models-4406
https://dev.to/embatec_astelo_918d3b2808/install-flutter-5c2k
https://dev.to/ndiaga/teaching-africa-through-ai-one-language-at-a-time-2dch

,Link,Title,Time Uploaded,Author,Tags,Reading Time,Article Content
0,https://dev.to/devteam/happy-11111101001-join-...,Happy 11111101001! Join our New Year Writing C...,2025-01-01T15:58:03Z,Jess Lee,#devchallenge#newyearchallenge#career#future,3 min read,"Happy New Year, everyone! Running through Febr..."
1,https://dev.to/sholajegede/part-2-master-authe...,Part 2: Master Authentication and Role-Based A...,2025-01-04T19:56:49Z,Shola Jegede,#kinde#convex#nextjs#tutorial,7 min read,This is the Part 2 to this post: In this guid...
2,https://dev.to/jetthoughts/why-ai-hasnt-blown-...,Why AI Hasn’t Blown Our Minds…Yet,2025-01-03T14:47:23Z,JetThoughts Dev,,3 min read,In a world buzzing with talk about artificial ...
3,https://dev.to/resource_bunk_1077cab07da/why-m...,Why Most Notion Templates Fail Businesses (And...,2025-01-04T17:55:59Z,Resource Bunk,#notion#beginners#tutorial#ai,3 min read,Notion templates have become an essential tool...
4,https://dev.to/0x3d_site/25-golang-resources-e...,🗂️ 25 Golang Resources Every Developer Will Fi...,2025-01-04T17:39:04Z,0x3d Site,#go#google#programming#productivity,12 min read,"Universal JSON, BSON, YAML, CSV, XML, mt940 ..."
5,https://dev.to/sonaykara/react-keeping-compone...,React : Keeping Components Pure,2025-01-04T21:52:44Z,Sonay Kara,#webdev#javascript#programming#react,2 min read,"If you like my articles, you can buy me a coff..."
6,https://dev.to/lovestaco/building-a-login-comp...,Building a Login Component with SSR Support Us...,2025-01-04T18:37:59Z,Athreya aka Maneshwar,#webdev#javascript#beginners#programming,2 min read,"At Hexmos, we needed a versatile login compone..."
7,https://dev.to/hanzla-baig/upcoming-challenges...,🌐 🌟 Upcoming Challenges On Dev.to 🚀,2025-01-03T02:47:59Z,Hanzla Baig,#agentai#githubchallenge#githubcopilot#devchal...,2 min read,Take flight with GitHub Copilot 🛫 Challenge S...
8,https://dev.to/kiraaziz/i-hate-website-builder...,I Hate Website Builders – So I Built My Own,2025-01-04T15:06:45Z,kiraaziz,#electron#nextjs#tailwindcss#webdev,2 min read,"Website builders should make life easier, but ..."
9,https://dev.to/makechi02/2024-a-year-of-resili...,"2024, A year of resilience, learning, and growth.",2025-01-04T20:07:19Z,Makechi™,#devchallenge#newyearchallenge#career#programming,2 min read,"Reflecting on 2024, it’s clear that this year ..."
10,https://dev.to/kcatucuamba/dominio-personaliza...,Dominio personalizado en Amazon API Gateway. D...,2025-01-04T17:24:22Z,Kevin Catucuamba,#aws#route53,4 min read,Cuando se implementan servicios utilizando Ama...
11,https://dev.to/eunit/five-advanced-techniques-...,Five Advanced Techniques to Improve Automated ...,2025-01-04T20:12:16Z,Emmanuel Uchenna,,8 min read,Software developers must stay ahead in nowada...
12,https://dev.to/shrsv/price-wage-profit-rent-14p7,Price = Wage + Profit + Rent,2025-01-04T19:18:47Z,Shrijith Venkatramana,#ai#management#programming#leadership,3 min read,"I'm Shrijith Venkatrama, the founder of Hexmos..."
13,https://dev.to/dhanushnehru/dev-retro-2024-jou...,Dev Retro 2024: Journey in review,2025-01-04T15:08:36Z,Dhanush N,#devchallenge#newyearchallenge#career#devresol...,3 min read,This is a submission for the : Retro’ing and D...
14,https://dev.to/chiragcodesweb/building-a-scala...,Building a Scalable Reverse Proxy Server like ...,2025-01-04T22:22:31Z,Chirag Singh,#node#nginx#javascript#programming,8 min read,"In today's microservices architecture, reverse..."
15,https://dev.to/yokwejuste/how-to-scan-in-golan...,How to Scan in GoLang,2025-01-04T11:25:19Z,Steve Yonkeu,#go#webdev#programming,2 min read,"In Go (golang), the fmt package provides sever..."
16,https://dev.to/yokwejuste/how-to-print-in-gola...,How to Print in GoLang,2025-01-04T11:15:21Z,Steve Yonkeu,#go#dev#tech#webdev,2 min read,It has always been a challenge for me when wor...
17,https://dev.to/stdlib/2024-retrospective-pip,2024 Retrospective,2025-01-04T21:16:29Z,Athan,#webdev#javascript#programming#node,15 min read,A look back at 2024 and a preview of the year ...
18,https://dev.to/kiran_baliga/retroing-and-debug...,Retro’ing and Debugging 2024: My Journey of Gr...,2025-01-04T22:13:17Z,Kiran Baliga,#devchallenge#newyearchallenge#career#beginners,2 min read,This is a submission for the : Retro’ing and D...
19,https://dev.to/dubjay18/the-power-of-context-i...,The Power of Context in Go: A Guide to Efficie...,2025-01-04T22:14:36Z,Dubjay18,#go#backend#webdev,2 min read,"When building robust, efficient, and maintaina..."
20,https://dev.to/harshm03/introduction-to-databa...,Introduction to Database Management Systems,2025-01-04T22:14:10Z,Harsh Mishra,#dbms#sql#mysql#computerscience,8 min read,Database Management Systems (DBMS) are an esse...
21,https://dev.to/alvaromontoro/human-writing-in-...,Human Writing in the Age of AI,2025-01-04T21:23:20Z,Alvaro Montoro,#opinion#ai,4 min read,A recurring thought when preparing articles on...
22,https://dev.to/okerew/new-version-for-my-osxie...,New version for my osxiec project,2025-01-04T21:27:53Z,Okerew,#osxiec#docker#macos,1 min read,"Published a new version of my software osxiec,..."
23,https://dev.to/youneshajizadeh/unpacking-the-b...,Unpacking the Benefits and Pitfalls of TypeScript,2025-01-04T21:38:04Z,younesHajizadeh,,4 min read,"As a developer, you may have found yourself as..."
24,https://dev.to/saidmounaim/dev-next-is-a-job-p...,"Dev Next is a job platform built with Next.js,...",2025-01-04T17:19:33Z,Said MOUNAIM,#webdev#javascript#programming#beginners,1 min read,Dev Next is a job platform built for developer...
25,https://dev.to/toptech5419/-week-11-of-100days...,### Week 11 of #100DaysOfCode 🚀: Responsive De...,2025-01-04T21:15:15Z,Alabi Temitope,#webdev#javascript#programming#softwaredevelop...,2 min read,This week was all about mastering responsivene...
26,https://dev.to/ahelmy/unlock-the-power-of-docu...,Unlock the Power of Docusaurus with AI,2025-01-04T21:19:14Z,Ali Helmy,#docusaurus#ai#rag#llm,2 min read,"In the ever-evolving world of documentation, D..."
27,https://dev.to/franciscomoretti/color-highligh...,Color Highlighting for Tailwind CSS Variables ...,2025-01-04T20:38:57Z,Francisco Moretti,#tailwindcss#vscode#tools#shadcnui,1 min read,When working with Tailwind CSS variables in VS...
28,https://dev.to/georgoulis/what-kind-of-data-te...,What kind of Data Team should I join?,2025-01-04T20:25:02Z,georgoulis,#dataengineering#datascience#data,1 min read,"When I landed my first job in Data, I didn’t a..."
29,https://dev.to/dubjay18/gos-must-pattern-strea...,Go's 'Must' Pattern: Streamline Your Error Han...,2025-01-04T20:29:58Z,Dubjay18,,3 min read,Error handling in Go is well known for its sim...
30,https://dev.to/pahlavaubivca/rust-registry-err...,"Rust registry error ""candidate versions found ...",2025-01-04T20:08:57Z,pahlavaubivca,,1 min read,Rare but pretty annoying error like:\n Appears...
31,https://dev.to/mikhailepatko/how-to-implement-...,How to implement JaCoCo in Kotlin + Spring Boo...,2025-01-04T09:12:47Z,Mikhail,,2 min read,"is a free code coverage library for Java, cre..."
32,https://dev.to/zerk4/laravel-debugbar-for-next...,Laravel Debugbar for Next.js,2025-01-04T19:52:33Z,Sebastian Pavel,#laravel#nextjs#typescript#php,2 min read,Working with Next.js as the frontend and Larav...
33,https://dev.to/rodbv/creating-a-to-do-app-with...,"Creating a To-Do app with Django and HTMX, par...",2025-01-04T21:28:30Z,rodbv,,4 min read,This is part 6 of a set of posts in which I am...
34,https://dev.to/madgan95/interface-standard-ove...,Interface Standard: Overview,2025-01-04T15:21:34Z,Madhav Ganesan,,3 min read,"It is a set of rules, specifications, and prot..."
35,https://dev.to/vishaaxl/build-an-otp-based-aut...,Build an OTP-Based Authentication Server with ...,2025-01-04T19:42:43Z,Vishal Shukla,#webdev#go#docker#twilio,6 min read,Begin by creating a new folder for your projec...
36,https://dev.to/master_mentee/how-i-set-up-my-c...,How I Set Up My Custom Domain and Email for Su...,2025-01-04T19:25:10Z,Keyul Patel,#cloudflare#domain#substack#writing,3 min read,"Happy New Year, fellow mentees 🎓! Last week, I..."
37,https://dev.to/blessedtechnologist/understandi...,Understanding Proof of Work in Blockchain,2025-01-04T19:16:26Z,Sanath Shenoy,#blockchain#bitcoin#web3#cryptocurrency,4 min read,Proof of Work (PoW) is a fundamental consensus...
38,https://dev.to/mellen/2025-what-is-it-good-for...,2025! What is it good for?,2025-01-04T21:08:54Z,Matt Ellen-Tsivintzeli,#devchallenge#newyearchallenge#career,2 min read,This is a submission for the : Compiling 2025....
39,https://dev.to/josemariairiarte/first-steps-wi...,First Steps in C++: An Introductory Capstone P...,2025-01-04T19:05:37Z,Jose Maria Iriarte,#cpp#beginners#softwareengineering#learning,3 min read,"In this article, I want to share the capstone ..."
40,https://dev.to/sourav_22cdd152890952704c/maste...,Mastering LangChain: Simplifying Complex Devel...,2025-01-04T19:08:23Z,Sourav,#webdev#javascript#ai#productivity,2 min read,"As a developer, you're always on the lookout f..."
41,https://dev.to/cheedge_lee/clusterip-vs-nodepo...,ClusterIP vs. NodePort,2025-01-04T19:06:32Z,Cheedge Lee,#clusterip#nodeport#kubernetes#cka,2 min read,ClusterIP\n NodePort\n The Endpoints object (1...
42,https://dev.to/sourav_22cdd152890952704c/react...,React 19 Unleashed 🚀: New Features Every Devel...,2025-01-04T18:59:06Z,Sourav,#webdev#javascript#programming#react,2 min read,React 19 introduces powerful new features that...
43,https://dev.to/yencolon/understanding-spring-s...,Understanding Spring Security: Building an Aut...,2025-01-04T18:56:54Z,Yen Colon,,3 min read,"Recently, while experimenting with Spring Boot..."
44,https://dev.to/razbakov/my-journey-with-ai-age...,My Journey with AI Agents: Revolutionizing WeD...,2025-01-04T18:16:44Z,Aleksey Razbakov,#ai#productivity#startup#webdev,2 min read,I have worked every day since the musicality f...
45,https://dev.to/airabbit/stop-repeating-termina...,Stop Repeating Terminal Command; Ask AI,2025-01-04T18:56:17Z,AIRabbit,,3 min read,"Let's face it, as developers we practically li..."
46,https://dev.to/xwero/laravel-route-alternative...,Laravel route alternatives,2025-01-04T20:36:13Z,david duymelinck,#php#laravel,2 min read,"Earlier today I reacted on a post about , and ..."
47,https://dev.to/emiroberti/aws-lambda-and-its-i...,AWS Lambda and Its Invocation Models,2025-01-04T15:32:21Z,Emi Roberti,#lambda#aws#serverless#cloud,3 min read,AWS Lambda is one of the most versatile and ef...
48,https://dev.to/embatec_astelo_918d3b2808/insta...,Install Flutter,2025-01-04T18:36:03Z,Embatec Astelo,#webdev#programming#beginners#flutter,1 min read,For months I started but failed to install Flu...
49,https://dev.to/ndiaga/teaching-africa-through-...,"Teaching Africa through AI, one language at a ...",2025-01-04T18:36:29Z,Ndiaga,#ai#education#opensource#africa,1 min read,"Over the next 5 years, Ndiaga Ka, a Computer S..."

## Getting the Word Count, Sentiment and Polarity Score of the Article Content

In [6]:
from nltk.corpus import stopwords
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer

df = merged_df
# Download the stopwords dataset
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('vader_lexicon')
nltk.download('punkt_tab')


def count_words_without_stopwords(text):
    if isinstance(text, (str, bytes)):
        words = nltk.word_tokenize(str(text))
        stop_words = set(stopwords.words('english'))
        filtered_words = [word for word in words if word.lower() not in stop_words]
        return len(filtered_words)
    else:
        0

df['Word Count'] = df['Article Content'].apply(count_words_without_stopwords)


sid = SentimentIntensityAnalyzer()

def get_sentiment(row):
    sentiment_scores = sid.polarity_scores(row)
    compound_score = sentiment_scores['compound']

    if compound_score >= 0.05:
        sentiment = 'Positive'
    elif compound_score <= -0.05:
        sentiment = 'Negative'
    else:
        sentiment = 'Neutral'

    return sentiment, compound_score

df[['Sentiment', 'Compound Score']] = df['Article Content'].astype(str).apply(lambda x: pd.Series(get_sentiment(x)))

df

[nltk_data] Downloading package stopwords to /home/gitpod/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /home/gitpod/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /home/gitpod/nltk_data...
[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/gitpod/nltk_data...
[nltk_data] Downloading package punkt_tab to /home/gitpod/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

,Link,Title,Time Uploaded,Author,Tags,Reading Time,Article Content,Word Count,Sentiment,Compound Score
0,https://dev.to/devteam/happy-11111101001-join-...,Happy 11111101001! Join our New Year Writing C...,2025-01-01T15:58:03Z,Jess Lee,#devchallenge#newyearchallenge#career#future,3 min read,"Happy New Year, everyone! Running through Febr...",235,Positive,0.9972
1,https://dev.to/sholajegede/part-2-master-authe...,Part 2: Master Authentication and Role-Based A...,2025-01-04T19:56:49Z,Shola Jegede,#kinde#convex#nextjs#tutorial,7 min read,This is the Part 2 to this post: In this guid...,670,Positive,0.9962
2,https://dev.to/jetthoughts/why-ai-hasnt-blown-...,Why AI Hasn’t Blown Our Minds…Yet,2025-01-03T14:47:23Z,JetThoughts Dev,,3 min read,In a world buzzing with talk about artificial ...,314,Positive,0.9900
3,https://dev.to/resource_bunk_1077cab07da/why-m...,Why Most Notion Templates Fail Businesses (And...,2025-01-04T17:55:59Z,Resource Bunk,#notion#beginners#tutorial#ai,3 min read,Notion templates have become an essential tool...,264,Positive,0.9966
4,https://dev.to/0x3d_site/25-golang-resources-e...,🗂️ 25 Golang Resources Every Developer Will Fi...,2025-01-04T17:39:04Z,0x3d Site,#go#google#programming#productivity,12 min read,"Universal JSON, BSON, YAML, CSV, XML, mt940 ...",446,Positive,0.9875
5,https://dev.to/sonaykara/react-keeping-compone...,React : Keeping Components Pure,2025-01-04T21:52:44Z,Sonay Kara,#webdev#javascript#programming#react,2 min read,"If you like my articles, you can buy me a coff...",214,Positive,0.9179
6,https://dev.to/lovestaco/building-a-login-comp...,Building a Login Component with SSR Support Us...,2025-01-04T18:37:59Z,Athreya aka Maneshwar,#webdev#javascript#beginners#programming,2 min read,"At Hexmos, we needed a versatile login compone...",191,Positive,0.9716
7,https://dev.to/hanzla-baig/upcoming-challenges...,🌐 🌟 Upcoming Challenges On Dev.to 🚀,2025-01-03T02:47:59Z,Hanzla Baig,#agentai#githubchallenge#githubcopilot#devchal...,2 min read,Take flight with GitHub Copilot 🛫 Challenge S...,177,Positive,0.9870
8,https://dev.to/kiraaziz/i-hate-website-builder...,I Hate Website Builders – So I Built My Own,2025-01-04T15:06:45Z,kiraaziz,#electron#nextjs#tailwindcss#webdev,2 min read,"Website builders should make life easier, but ...",129,Positive,0.8045
9,https://dev.to/makechi02/2024-a-year-of-resili...,"2024, A year of resilience, learning, and growth.",2025-01-04T20:07:19Z,Makechi™,#devchallenge#newyearchallenge#career#programming,2 min read,"Reflecting on 2024, it’s clear that this year ...",286,Positive,0.9948
10,https://dev.to/kcatucuamba/dominio-personaliza...,Dominio personalizado en Amazon API Gateway. D...,2025-01-04T17:24:22Z,Kevin Catucuamba,#aws#route53,4 min read,Cuando se implementan servicios utilizando Ama...,592,Positive,0.4767
11,https://dev.to/eunit/five-advanced-techniques-...,Five Advanced Techniques to Improve Automated ...,2025-01-04T20:12:16Z,Emmanuel Uchenna,,8 min read,Software developers must stay ahead in nowada...,667,Positive,0.9992
12,https://dev.to/shrsv/price-wage-profit-rent-14p7,Price = Wage + Profit + Rent,2025-01-04T19:18:47Z,Shrijith Venkatramana,#ai#management#programming#leadership,3 min read,"I'm Shrijith Venkatrama, the founder of Hexmos...",390,Positive,0.9987
13,https://dev.to/dhanushnehru/dev-retro-2024-jou...,Dev Retro 2024: Journey in review,2025-01-04T15:08:36Z,Dhanush N,#devchallenge#newyearchallenge#career#devresol...,3 min read,This is a submission for the : Retro’ing and D...,436,Positive,0.9988
14,https://dev.to/chiragcodesweb/building-a-scala...,Building a Scalable Reverse Proxy Server like ...,2025-01-04T22:22:31Z,Chirag Singh,#node#nginx#javascript#programming,8 min read,"In today's microservices architecture, reverse...",733,Positive,0.9983
15,https://dev.to/yokwejuste/how-to-scan-in-golan...,How to Scan in GoLang,2025-01-04T11:25:19Z,Steve Yonkeu,#go#webdev#programming,2 min read,"In Go (golang), the fmt package provides sever...",72,Positive,0.4404
16,https://dev.to/yokwejuste/how-to-print-in-gola...,How to Print in GoLang,2025-01-04T11:15:21Z,Steve Yonkeu,#go#dev#tech#webdev,2 min read,It has always been a challenge for me when wor...,101,Positive,0.0772
17,https://dev.to/stdlib/2024-retrospective-pip,2024 Retrospective,2025-01-04T21:16:29Z,Athan,#webdev#javascript#programming#node,15 min read,A look back at 2024 and a preview of the year ...,1454,Positive,0.9998
18,https://dev.to/kiran_baliga/retroing-and-debug...,Retro’ing and Debugging 2024: My Journey of Gr...,2025-01-04T22:13:17Z,Kiran Baliga,#devchallenge#newyearchallenge#career#beginners,2 min read,This is a submission for the : Retro’ing and D...,343,Positive,0.9965
19,https://dev.to/dubjay18/the-power-of-context-i...,The Power of Context in Go: A Guide to Efficie...,2025-01-04T22:14:36Z,Dubjay18,#go#backend#webdev,2 min read,"When building robust, efficient, and maintaina...",153,Positive,0.9349
20,https://dev.to/harshm03/introduction-to-databa...,Introduction to Database Management Systems,2025-01-04T22:14:10Z,Harsh Mishra,#dbms#sql#mysql#computerscience,8 min read,Database Management Systems (DBMS) are an esse...,427,Positive,0.9884
21,https://dev.to/alvaromontoro/human-writing-in-...,Human Writing in the Age of AI,2025-01-04T21:23:20Z,Alvaro Montoro,#opinion#ai,4 min read,A recurring thought when preparing articles on...,546,Positive,0.9682
22,https://dev.to/okerew/new-version-for-my-osxie...,New version for my osxiec project,2025-01-04T21:27:53Z,Okerew,#osxiec#docker#macos,1 min read,"Published a new version of my software osxiec,...",12,Positive,0.4019
23,https://dev.to/youneshajizadeh/unpacking-the-b...,Unpacking the Benefits and Pitfalls of TypeScript,2025-01-04T21:38:04Z,younesHajizadeh,,4 min read,"As a developer, you may have found yourself as...",654,Positive,0.9994
24,https://dev.to/saidmounaim/dev-next-is-a-job-p...,"Dev Next is a job platform built with Next.js,...",2025-01-04T17:19:33Z,Said MOUNAIM,#webdev#javascript#programming#beginners,1 min read,Dev Next is a job platform built for developer...,85,Positive,0.8750
25,https://dev.to/toptech5419/-week-11-of-100days...,### Week 11 of #100DaysOfCode 🚀: Responsive De...,2025-01-04T21:15:15Z,Alabi Temitope,#webdev#javascript#programming#softwaredevelop...,2 min read,This week was all about mastering responsivene...,81,Positive,0.9669
26,https://dev.to/ahelmy/unlock-the-power-of-docu...,Unlock the Power of Docusaurus with AI,2025-01-04T21:19:14Z,Ali Helmy,#docusaurus#ai#rag#llm,2 min read,"In the ever-evolving world of documentation, D...",210,Positive,0.9812
27,https://dev.to/franciscomoretti/color-highligh...,Color Highlighting for Tailwind CSS Variables ...,2025-01-04T20:38:57Z,Francisco Moretti,#tailwindcss#vscode#tools#shadcnui,1 min read,When working with Tailwind CSS variables in VS...,86,Positive,0.9184
28,https://dev.to/georgoulis/what-kind-of-data-te...,What kind of Data Team should I join?,2025-01-04T20:25:02Z,georgoulis,#dataengineering#datascience#data,1 min read,"When I landed my first job in Data, I didn’t a...",117,Positive,0.9408
29,https://dev.to/dubjay18/gos-must-pattern-strea...,Go's 'Must' Pattern: Streamline Your Error Han...,2025-01-04T20:29:58Z,Dubjay18,,3 min read,Error handling in Go is well known for its sim...,407,Negative,-0.3316
30,https://dev.to/pahlavaubivca/rust-registry-err...,"Rust registry error ""candidate versions found ...",2025-01-04T20:08:57Z,pahlavaubivca,,1 min read,Rare but pretty annoying error like:\n Appears...,69,Negative,-0.8439
31,https://dev.to/mikhailepatko/how-to-implement-...,How to implement JaCoCo in Kotlin + Spring Boo...,2025-01-04T09:12:47Z,Mikhail,,2 min read,"is a free code coverage library for Java, cre...",80,Positive,0.7506
32,https://dev.to/zerk4/laravel-debugbar-for-next...,Laravel Debugbar for Next.js,2025-01-04T19:52:33Z,Sebastian Pavel,#laravel#nextjs#typescript#php,2 min read,Working with Next.js as the frontend and Larav...,145,Positive,0.9707
33,https://dev.to/rodbv/creating-a-to-do-app-with...,"Creating a To-Do app with Django and HTMX, par...",2025-01-04T21:28:30Z,rodbv,,4 min read,This is part 6 of a set of posts in which I am...,254,Negative,-0.7540
34,https://dev.to/madgan95/interface-standard-ove...,Interface Standard: Overview,2025-01-04T15:21:34Z,Madhav Ganesan,,3 min read,"It is a set of rules, specifications, and prot...",279,Positive,0.9312
35,https://dev.to/vishaaxl/build-an-otp-based-aut...,Build an OTP-Based Authentication Server with ...,2025-01-04T19:42:43Z,Vishal Shukla,#webdev#go#docker#twilio,6 min read,Begin by creating a new folder for your projec...,305,Positive,0.9777
36,https://dev.to/master_mentee/how-i-set-up-my-c...,How I Set Up My Custom Domain and Email for Su...,2025-01-04T19:25:10Z,Keyul Patel,#cloudflare#domain#substack#writing,3 min read,"Happy New Year, fellow mentees 🎓! Last week, I...",393,Positive,0.9993
37,https://dev.to/blessedtechnologist/understandi...,Understanding Proof of Work in Blockchain,2025-01-04T19:16:26Z,Sanath Shenoy,#blockchain#bitcoin#web3#cryptocurrency,4 min read,Proof of Work (PoW) is a fundamental consensus...,765,Negative,-0.2459
38,https://dev.to/mellen/2025-what-is-it-good-for...,2025! What is it good for?,2025-01-04T21:08:54Z,Matt Ellen-Tsivintzeli,#devchallenge#newyearchallenge#career,2 min read,This is a submission for the : Compiling 2025....,169,Positive,0.9586
39,https://dev.to/josemariairiarte/first-steps-wi...,First Steps in C++: An Introductory Capstone P...,2025-01-04T19:05:37Z,Jose Maria Iriarte,#cpp#beginners#softwareengineering#learning,3 min read,"In this article, I want to share the capstone ...",698,Positive,0.9968
40,https://dev.to/sourav_22cdd152890952704c/maste...,Mastering LangChain: Simplifying Complex Devel...,2025-01-04T19:08:23Z,Sourav,#webdev#javascript#ai#productivity,2 min read,"As a developer, you're always on the lookout f...",235,Positive,0.9935
41,https://dev.to/cheedge_lee/clusterip-vs-nodepo...,ClusterIP vs. NodePort,2025-01-04T19:06:32Z,Cheedge Lee,#clusterip#nodeport#kubernetes#cka,2 min read,ClusterIP\n NodePort\n The Endpoints object (1...,33,Neutral,0.0000
42,https://dev.to/sourav_22cdd152890952704c/react...,React 19 Unleashed 🚀: New Features Every Devel...,2025-01-04T18:59:06Z,Sourav,#webdev#javascript#programming#react,2 min read,React 19 introduces powerful new features that...,150,Positive,0.9772
43,https://dev.to/yencolon/understanding-spring-s...,Understanding Spring Security: Building an Aut...,2025-01-04T18:56:54Z,Yen Colon,,3 min read,"Recently, while experimenting with Spring Boot...",221,Positive,0.9584
44,https://dev.to/razbakov/my-journey-with-ai-age...,My Journey with AI Agents: Revolutionizing WeD...,2025-01-04T18:16:44Z,Aleksey Razbakov,#ai#productivity#startup#webdev,2 min read,I have worked every day since the musicality f...,257,Positive,0.9927
45,https://dev.to/airabbit/stop-repeating-termina...,Stop Repeating Terminal Command; Ask AI,2025-01-04T18:56:17Z,AIRabbit,,3 min read,"Let's face it, as developers we practically li...",239,Positive,0.9950
46,https://dev.to/xwero/laravel-route-alternative...,Laravel route alternatives,2025-01-04T20:36:13Z,david duymelinck,#php#laravel,2 min read,"Earlier today I reacted on a post about , and ...",182,Positive,0.9368
47,https://dev.to/emiroberti/aws-lambda-and-its-i...,AWS Lambda and Its Invocation Models,2025-01-04T15:32:21Z,Emi Roberti,#lambda#aws#serverless#cloud,3 min read,AWS Lambda is one of the most versatile and ef...,526,Positive,0.9863
48,https://dev.to/embatec_astelo_918d3b2808/insta...,Install Flutter,2025-01-04T18:36:03Z,Embatec Astelo,#webdev#programming#beginners#flutter,1 min read,For months I started but failed to install Flu...,63,Negative,-0.8563
49,https://dev.to/ndiaga/teaching-africa-through-...,"Teaching Africa through AI, one language at a ...",2025-01-04T18:36:29Z,Ndiaga,#ai#education#opensource#africa,1 min read,"Over the next 5 years, Ndiaga Ka, a Computer S...",33,Neutral,0.0000

## Detecting the Language of each Article Content

In [7]:
import pandas as pd
import langid
import pycountry


def detect_language(text):
    # Convert NaN to an empty string
    text = str(text) if pd.notna(text) else ''
    
    # Use langid to detect the language
    lang, confidence = langid.classify(text)
    return lang

df['Language'] = df['Article Content'].apply(detect_language)
df['Language'] = df['Language'].map(lambda code: pycountry.languages.get(alpha_2=code).name if pycountry.languages.get(alpha_2=code) else code)
df

,Link,Title,Time Uploaded,Author,Tags,Reading Time,Article Content,Word Count,Sentiment,Compound Score,Language
0,https://dev.to/devteam/happy-11111101001-join-...,Happy 11111101001! Join our New Year Writing C...,2025-01-01T15:58:03Z,Jess Lee,#devchallenge#newyearchallenge#career#future,3 min read,"Happy New Year, everyone! Running through Febr...",235,Positive,0.9972,English
1,https://dev.to/sholajegede/part-2-master-authe...,Part 2: Master Authentication and Role-Based A...,2025-01-04T19:56:49Z,Shola Jegede,#kinde#convex#nextjs#tutorial,7 min read,This is the Part 2 to this post: In this guid...,670,Positive,0.9962,English
2,https://dev.to/jetthoughts/why-ai-hasnt-blown-...,Why AI Hasn’t Blown Our Minds…Yet,2025-01-03T14:47:23Z,JetThoughts Dev,,3 min read,In a world buzzing with talk about artificial ...,314,Positive,0.9900,English
3,https://dev.to/resource_bunk_1077cab07da/why-m...,Why Most Notion Templates Fail Businesses (And...,2025-01-04T17:55:59Z,Resource Bunk,#notion#beginners#tutorial#ai,3 min read,Notion templates have become an essential tool...,264,Positive,0.9966,English
4,https://dev.to/0x3d_site/25-golang-resources-e...,🗂️ 25 Golang Resources Every Developer Will Fi...,2025-01-04T17:39:04Z,0x3d Site,#go#google#programming#productivity,12 min read,"Universal JSON, BSON, YAML, CSV, XML, mt940 ...",446,Positive,0.9875,English
5,https://dev.to/sonaykara/react-keeping-compone...,React : Keeping Components Pure,2025-01-04T21:52:44Z,Sonay Kara,#webdev#javascript#programming#react,2 min read,"If you like my articles, you can buy me a coff...",214,Positive,0.9179,English
6,https://dev.to/lovestaco/building-a-login-comp...,Building a Login Component with SSR Support Us...,2025-01-04T18:37:59Z,Athreya aka Maneshwar,#webdev#javascript#beginners#programming,2 min read,"At Hexmos, we needed a versatile login compone...",191,Positive,0.9716,English
7,https://dev.to/hanzla-baig/upcoming-challenges...,🌐 🌟 Upcoming Challenges On Dev.to 🚀,2025-01-03T02:47:59Z,Hanzla Baig,#agentai#githubchallenge#githubcopilot#devchal...,2 min read,Take flight with GitHub Copilot 🛫 Challenge S...,177,Positive,0.9870,English
8,https://dev.to/kiraaziz/i-hate-website-builder...,I Hate Website Builders – So I Built My Own,2025-01-04T15:06:45Z,kiraaziz,#electron#nextjs#tailwindcss#webdev,2 min read,"Website builders should make life easier, but ...",129,Positive,0.8045,English
9,https://dev.to/makechi02/2024-a-year-of-resili...,"2024, A year of resilience, learning, and growth.",2025-01-04T20:07:19Z,Makechi™,#devchallenge#newyearchallenge#career#programming,2 min read,"Reflecting on 2024, it’s clear that this year ...",286,Positive,0.9948,English
10,https://dev.to/kcatucuamba/dominio-personaliza...,Dominio personalizado en Amazon API Gateway. D...,2025-01-04T17:24:22Z,Kevin Catucuamba,#aws#route53,4 min read,Cuando se implementan servicios utilizando Ama...,592,Positive,0.4767,Spanish
11,https://dev.to/eunit/five-advanced-techniques-...,Five Advanced Techniques to Improve Automated ...,2025-01-04T20:12:16Z,Emmanuel Uchenna,,8 min read,Software developers must stay ahead in nowada...,667,Positive,0.9992,English
12,https://dev.to/shrsv/price-wage-profit-rent-14p7,Price = Wage + Profit + Rent,2025-01-04T19:18:47Z,Shrijith Venkatramana,#ai#management#programming#leadership,3 min read,"I'm Shrijith Venkatrama, the founder of Hexmos...",390,Positive,0.9987,English
13,https://dev.to/dhanushnehru/dev-retro-2024-jou...,Dev Retro 2024: Journey in review,2025-01-04T15:08:36Z,Dhanush N,#devchallenge#newyearchallenge#career#devresol...,3 min read,This is a submission for the : Retro’ing and D...,436,Positive,0.9988,English
14,https://dev.to/chiragcodesweb/building-a-scala...,Building a Scalable Reverse Proxy Server like ...,2025-01-04T22:22:31Z,Chirag Singh,#node#nginx#javascript#programming,8 min read,"In today's microservices architecture, reverse...",733,Positive,0.9983,English
15,https://dev.to/yokwejuste/how-to-scan-in-golan...,How to Scan in GoLang,2025-01-04T11:25:19Z,Steve Yonkeu,#go#webdev#programming,2 min read,"In Go (golang), the fmt package provides sever...",72,Positive,0.4404,English
16,https://dev.to/yokwejuste/how-to-print-in-gola...,How to Print in GoLang,2025-01-04T11:15:21Z,Steve Yonkeu,#go#dev#tech#webdev,2 min read,It has always been a challenge for me when wor...,101,Positive,0.0772,English
17,https://dev.to/stdlib/2024-retrospective-pip,2024 Retrospective,2025-01-04T21:16:29Z,Athan,#webdev#javascript#programming#node,15 min read,A look back at 2024 and a preview of the year ...,1454,Positive,0.9998,English
18,https://dev.to/kiran_baliga/retroing-and-debug...,Retro’ing and Debugging 2024: My Journey of Gr...,2025-01-04T22:13:17Z,Kiran Baliga,#devchallenge#newyearchallenge#career#beginners,2 min read,This is a submission for the : Retro’ing and D...,343,Positive,0.9965,English
19,https://dev.to/dubjay18/the-power-of-context-i...,The Power of Context in Go: A Guide to Efficie...,2025-01-04T22:14:36Z,Dubjay18,#go#backend#webdev,2 min read,"When building robust, efficient, and maintaina...",153,Positive,0.9349,English
20,https://dev.to/harshm03/introduction-to-databa...,Introduction to Database Management Systems,2025-01-04T22:14:10Z,Harsh Mishra,#dbms#sql#mysql#computerscience,8 min read,Database Management Systems (DBMS) are an esse...,427,Positive,0.9884,English
21,https://dev.to/alvaromontoro/human-writing-in-...,Human Writing in the Age of AI,2025-01-04T21:23:20Z,Alvaro Montoro,#opinion#ai,4 min read,A recurring thought when preparing articles on...,546,Positive,0.9682,English
22,https://dev.to/okerew/new-version-for-my-osxie...,New version for my osxiec project,2025-01-04T21:27:53Z,Okerew,#osxiec#docker#macos,1 min read,"Published a new version of my software osxiec,...",12,Positive,0.4019,English
23,https://dev.to/youneshajizadeh/unpacking-the-b...,Unpacking the Benefits and Pitfalls of TypeScript,2025-01-04T21:38:04Z,younesHajizadeh,,4 min read,"As a developer, you may have found yourself as...",654,Positive,0.9994,English
24,https://dev.to/saidmounaim/dev-next-is-a-job-p...,"Dev Next is a job platform built with Next.js,...",2025-01-04T17:19:33Z,Said MOUNAIM,#webdev#javascript#programming#beginners,1 min read,Dev Next is a job platform built for developer...,85,Positive,0.8750,English
25,https://dev.to/toptech5419/-week-11-of-100days...,### Week 11 of #100DaysOfCode 🚀: Responsive De...,2025-01-04T21:15:15Z,Alabi Temitope,#webdev#javascript#programming#softwaredevelop...,2 min read,This week was all about mastering responsivene...,81,Positive,0.9669,English
26,https://dev.to/ahelmy/unlock-the-power-of-docu...,Unlock the Power of Docusaurus with AI,2025-01-04T21:19:14Z,Ali Helmy,#docusaurus#ai#rag#llm,2 min read,"In the ever-evolving world of documentation, D...",210,Positive,0.9812,English
27,https://dev.to/franciscomoretti/color-highligh...,Color Highlighting for Tailwind CSS Variables ...,2025-01-04T20:38:57Z,Francisco Moretti,#tailwindcss#vscode#tools#shadcnui,1 min read,When working with Tailwind CSS variables in VS...,86,Positive,0.9184,English
28,https://dev.to/georgoulis/what-kind-of-data-te...,What kind of Data Team should I join?,2025-01-04T20:25:02Z,georgoulis,#dataengineering#datascience#data,1 min read,"When I landed my first job in Data, I didn’t a...",117,Positive,0.9408,English
29,https://dev.to/dubjay18/gos-must-pattern-strea...,Go's 'Must' Pattern: Streamline Your Error Han...,2025-01-04T20:29:58Z,Dubjay18,,3 min read,Error handling in Go is well known for its sim...,407,Negative,-0.3316,English
30,https://dev.to/pahlavaubivca/rust-registry-err...,"Rust registry error ""candidate versions found ...",2025-01-04T20:08:57Z,pahlavaubivca,,1 min read,Rare but pretty annoying error like:\n Appears...,69,Negative,-0.8439,English
31,https://dev.to/mikhailepatko/how-to-implement-...,How to implement JaCoCo in Kotlin + Spring Boo...,2025-01-04T09:12:47Z,Mikhail,,2 min read,"is a free code coverage library for Java, cre...",80,Positive,0.7506,English
32,https://dev.to/zerk4/laravel-debugbar-for-next...,Laravel Debugbar for Next.js,2025-01-04T19:52:33Z,Sebastian Pavel,#laravel#nextjs#typescript#php,2 min read,Working with Next.js as the frontend and Larav...,145,Positive,0.9707,English
33,https://dev.to/rodbv/creating-a-to-do-app-with...,"Creating a To-Do app with Django and HTMX, par...",2025-01-04T21:28:30Z,rodbv,,4 min read,This is part 6 of a set of posts in which I am...,254,Negative,-0.7540,English
34,https://dev.to/madgan95/interface-standard-ove...,Interface Standard: Overview,2025-01-04T15:21:34Z,Madhav Ganesan,,3 min read,"It is a set of rules, specifications, and prot...",279,Positive,0.9312,English
35,https://dev.to/vishaaxl/build-an-otp-based-aut...,Build an OTP-Based Authentication Server with ...,2025-01-04T19:42:43Z,Vishal Shukla,#webdev#go#docker#twilio,6 min read,Begin by creating a new folder for your projec...,305,Positive,0.9777,English
36,https://dev.to/master_mentee/how-i-set-up-my-c...,How I Set Up My Custom Domain and Email for Su...,2025-01-04T19:25:10Z,Keyul Patel,#cloudflare#domain#substack#writing,3 min read,"Happy New Year, fellow mentees 🎓! Last week, I...",393,Positive,0.9993,English
37,https://dev.to/blessedtechnologist/understandi...,Understanding Proof of Work in Blockchain,2025-01-04T19:16:26Z,Sanath Shenoy,#blockchain#bitcoin#web3#cryptocurrency,4 min read,Proof of Work (PoW) is a fundamental consensus...,765,Negative,-0.2459,English
38,https://dev.to/mellen/2025-what-is-it-good-for...,2025! What is it good for?,2025-01-04T21:08:54Z,Matt Ellen-Tsivintzeli,#devchallenge#newyearchallenge#career,2 min read,This is a submission for the : Compiling 2025....,169,Positive,0.9586,English
39,https://dev.to/josemariairiarte/first-steps-wi...,First Steps in C++: An Introductory Capstone P...,2025-01-04T19:05:37Z,Jose Maria Iriarte,#cpp#beginners#softwareengineering#learning,3 min read,"In this article, I want to share the capstone ...",698,Positive,0.9968,English
40,https://dev.to/sourav_22cdd152890952704c/maste...,Mastering LangChain: Simplifying Complex Devel...,2025-01-04T19:08:23Z,Sourav,#webdev#javascript#ai#productivity,2 min read,"As a developer, you're always on the lookout f...",235,Positive,0.9935,English
41,https://dev.to/cheedge_lee/clusterip-vs-nodepo...,ClusterIP vs. NodePort,2025-01-04T19:06:32Z,Cheedge Lee,#clusterip#nodeport#kubernetes#cka,2 min read,ClusterIP\n NodePort\n The Endpoints object (1...,33,Neutral,0.0000,English
42,https://dev.to/sourav_22cdd152890952704c/react...,React 19 Unleashed 🚀: New Features Every Devel...,2025-01-04T18:59:06Z,Sourav,#webdev#javascript#programming#react,2 min read,React 19 introduces powerful new features that...,150,Positive,0.9772,English
43,https://dev.to/yencolon/understanding-spring-s...,Understanding Spring Security: Building an Aut...,2025-01-04T18:56:54Z,Yen Colon,,3 min read,"Recently, while experimenting with Spring Boot...",221,Positive,0.9584,English
44,https://dev.to/razbakov/my-journey-with-ai-age...,My Journey with AI Agents: Revolutionizing WeD...,2025-01-04T18:16:44Z,Aleksey Razbakov,#ai#productivity#startup#webdev,2 min read,I have worked every day since the musicality f...,257,Positive,0.9927,English
45,https://dev.to/airabbit/stop-repeating-termina...,Stop Repeating Terminal Command; Ask AI,2025-01-04T18:56:17Z,AIRabbit,,3 min read,"Let's face it, as developers we practically li...",239,Positive,0.9950,English
46,https://dev.to/xwero/laravel-route-alternative...,Laravel route alternatives,2025-01-04T20:36:13Z,david duymelinck,#php#laravel,2 min read,"Earlier today I reacted on a post about , and ...",182,Positive,0.9368,English
47,https://dev.to/emiroberti/aws-lambda-and-its-i...,AWS Lambda and Its Invocation Models,2025-01-04T15:32:21Z,Emi Roberti,#lambda#aws#serverless#cloud,3 min read,AWS Lambda is one of the most versatile and ef...,526,Positive,0.9863,English
48,https://dev.to/embatec_astelo_918d3b2808/insta...,Install Flutter,2025-01-04T18:36:03Z,Embatec Astelo,#webdev#programming#beginners#flutter,1 min read,For months I started but failed to install Flu...,63,Negative,-0.8563,English
49,https://dev.to/ndiaga/teaching-africa-through-...,"Teaching Africa through AI, one language at a ...",2025-01-04T18:36:29Z,Ndiaga,#ai#education#opensource#africa,1 min read,"Over the next 5 years, Ndiaga Ka, a Computer S...",33,Neutral,0.0000,English

## Testing for successful handshake

In [5]:

from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = os.environ['URI_KEY']

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

## Moving our data to MongoDB Atlas

In [6]:
uri = os.environ['URI_KEY']


# Specify the database and collection
db = client['my_database']  # Create/use 'my_database'
collection = db['article_collection']  # Create/use 'my_collection'

# Convert DataFrame to dictionary (list of dictionaries)
data = df.to_dict(orient='records')

# Insert the data into the MongoDB collection
result = collection.insert_many(data)

# Print the inserted IDs
print("Inserted document IDs:", result.inserted_ids)



# Step 1: Identify duplicates
pipeline = [
    {
        "$group": {
            "_id": "$Link",  # Field to check for duplicates
            "uniqueIds": { "$addToSet": "$_id" },  # Store all unique _ids
            "count": { "$sum": 1 }  # Count duplicates
        }
    },
    {
        "$match": {
            "count": { "$gt": 1 }  # Only keep duplicates
        }
    }
]

duplicates = collection.aggregate(pipeline)

# Step 2: Remove duplicates
for doc in duplicates:
    unique_ids = doc['uniqueIds']
    unique_ids.pop(0)  # Keep the first id
    # Delete the duplicates
    collection.delete_many({"_id": {"$in": unique_ids}})

print("Duplicates removed.")

Inserted document IDs: [ObjectId('671180b7c829e33e5b3d7c41'), ObjectId('671180b7c829e33e5b3d7c42'), ObjectId('671180b7c829e33e5b3d7c43'), ObjectId('671180b7c829e33e5b3d7c44'), ObjectId('671180b7c829e33e5b3d7c45'), ObjectId('671180b7c829e33e5b3d7c46'), ObjectId('671180b7c829e33e5b3d7c47'), ObjectId('671180b7c829e33e5b3d7c48'), ObjectId('671180b7c829e33e5b3d7c49'), ObjectId('671180b7c829e33e5b3d7c4a'), ObjectId('671180b7c829e33e5b3d7c4b'), ObjectId('671180b7c829e33e5b3d7c4c'), ObjectId('671180b7c829e33e5b3d7c4d'), ObjectId('671180b7c829e33e5b3d7c4e'), ObjectId('671180b7c829e33e5b3d7c4f'), ObjectId('671180b7c829e33e5b3d7c50'), ObjectId('671180b7c829e33e5b3d7c51'), ObjectId('671180b7c829e33e5b3d7c52'), ObjectId('671180b7c829e33e5b3d7c53'), ObjectId('671180b7c829e33e5b3d7c54'), ObjectId('671180b7c829e33e5b3d7c55'), ObjectId('671180b7c829e33e5b3d7c56'), ObjectId('671180b7c829e33e5b3d7c57'), ObjectId('671180b7c829e33e5b3d7c58'), ObjectId('671180b7c829e33e5b3d7c59'), ObjectId('671180b7c829e33e5b3d7c5a'), ObjectId('671180b7c829e33e5b3d7c5b'), ObjectId('671180b7c829e33e5b3d7c5c'), ObjectId('671180b7c829e33e5b3d7c5d'), ObjectId('671180b7c829e33e5b3d7c5e'), ObjectId('671180b7c829e33e5b3d7c5f'), ObjectId('671180b7c829e33e5b3d7c60'), ObjectId('671180b7c829e33e5b3d7c61'), ObjectId('671180b7c829e33e5b3d7c62'), ObjectId('671180b7c829e33e5b3d7c63'), ObjectId('671180b7c829e33e5b3d7c64'), ObjectId('671180b7c829e33e5b3d7c65'), ObjectId('671180b7c829e33e5b3d7c66'), ObjectId('671180b7c829e33e5b3d7c67'), ObjectId('671180b7c829e33e5b3d7c68'), ObjectId('671180b7c829e33e5b3d7c69'), ObjectId('671180b7c829e33e5b3d7c6a'), ObjectId('671180b7c829e33e5b3d7c6b'), ObjectId('671180b7c829e33e5b3d7c6c'), ObjectId('671180b7c829e33e5b3d7c6d'), ObjectId('671180b7c829e33e5b3d7c6e'), ObjectId('671180b7c829e33e5b3d7c6f'), ObjectId('671180b7c829e33e5b3d7c70'), ObjectId('671180b7c829e33e5b3d7c71'), ObjectId('671180b7c829e33e5b3d7c72')]
Duplicates removed.

In [1]:
import streamlit as st
import matplotlib.pyplot as plt
import seaborn as sns
from wordcloud import WordCloud
from pymongo import MongoClient
from pymongo.server_api import ServerApi
import pandas as pd
from nltk.corpus import stopwords
import nltk
from dotenv import load_dotenv
import os
load_dotenv()

# MongoDB connection details
uri = os.environ['URI_KEY']
client = MongoClient(uri, server_api=ServerApi('1'))
db = client['my_database']  # Create/use 'my_database'
collection = db['article_collection'] 

# Load MongoDB data
data = pd.DataFrame(list(collection.find()))

In [13]:
data
df = data[data['Author'].str.contains('Ivanha Paz', case=False, na=False)]

df

#min_word_count = int(df['Word Count'].min())
max_word_count = int(data['Word Count'].min())
max_word_count

0